### PR TITLE
apicaffe_cleanup into develop

### PR DESCRIPTION
**Pull request by drinkingkazu**
apicaffe_cleanup branch is ready to be merged into develop, I believe.

### CODE REVIEW

**Comment by drinkingkazu** [comment]
... and of course I am happy to resolve conflict

**Comment by drinkingkazu** [comment]
Conflict is resolved. @vgenty @erezcoh4  @twongjirad @ahack379 @coreyjadams I would like to merge this branch back into develop. Please give a go, and would be great if you can even test it!

**Comment by erezcoh4** [comment]
sounds great! would gladly help test it

**Comment by drinkingkazu** [comment]
For testing apicaffe_cleanup branch, if anyone can try what "you used to do w/ develop branch" with this release candidates. If works, test pass :)

In future it should use a set of unit test, a development of unit test may be coordinated with this effort https://github.com/LArbys/LArCV/issues/51 but by no means we should delay the release.

A release candidate for develop branch before this merge is also made: https://github.com/LArbys/LArCV/tree/release/v01.00.00

**Comment by twongjirad** [comment]
Crap. I fear I mess this up with my PR.

**Comment by twongjirad** [comment]
Looked into the conflict. Am I right, supera.fcl is symlinked to

/Users/kazuhiro/PlayGit/LArCV/app/Supera/larfmwk_shared/supera.fcl ?

This can't be right. Is the intention to bring this file into the repository?

**Comment by drinkingkazu** [comment]
Brought up to date w/ develop. 

@twongjirad the symbolic link was intentional to share an "example" configuration file among larsoft and larlite interface so that we avoid a mistake of "oh I updated here but forgot there" kind of things. not important so I just pushed a new replacement (physical file instead of symbolic link).

**Comment by erezcoh4** [comment]
Kazu, could you please make the following modification? I am having problems w/ CV2layout that might occur to other users as well, and the only way to load view_rgb is by relaxing its requirement   

in mac/pyrgb/display/rgbdisplay.py, in line 259, change from 
        self.cv2_layout = CV2Layout()
to
        try:
            self.cv2_layout = CV2Layout()
        except:
            print "no CV2"
            self.cv2_layout = None
            pass

**Comment by drinkingkazu** [comment]
@erezcoh4 Is this something already fixed in develop? If so, this will be in place once merged!

**Comment by drinkingkazu** [comment]
@erezcoh4 I see similar lines in develop here:
https://github.com/LArbys/LArCV/blob/develop/mac/pyrgb/display/rgbdisplay.py#L20-L23

If that works for you then we will have it once merged :)

**Comment by drinkingkazu** [comment]
@ahack379 confirmed her module (tested under PlayGround) works fine

**Pull request merged**
