### PR TITLE
Merge clustering tool into develop

### PR DESCRIPTION
**Pull request by twongjirad**
Request is to merge clustering tools (the module DBSCAN) into develop. I have been using this for the cosmic pixel taggers.  DBSCAN is dependent on library that does fairly fast nearest neighbor comparisons (through the use of trees).  This library is included in the repo in app/ann_1.1.2 and is configured to build out of the box.  The configure script should DBSCAN also by default.  Whether or not it builds is dependent on the LARCV_ANN environment variable which can be set inside the configure script.

### CODE REVIEW

**Comment by twongjirad** [comment]
I request that someone checkout this branch fresh and try to build it. I want to make sure I didn't miss anything.

**Comment by twongjirad** [comment]
oh. there are also a couple of added CVUtil functions I found useful for dealing with opencv objects in C++.

**Comment by vgenty** [comment]
Here in 10.11.6 I get this compiler error
https://goo.gl/CIGPtC

`libtool: unrecognized option '-static'`

Clang info
`Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by vgenty** [comment]
Ah -- and my libtool version

libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by vgenty** [comment]
Trying out with Xcode libtool instead... forgot this happens sometimes (using GNU libtool over what's in CommandLineTools)

Now the error I get:
https://goo.gl/MRR8na

**Comment by vgenty** [comment]
Same result on linux with fresh build

https://goo.gl/omF2gM

`gcc --version`
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`libtool --version`
libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by twongjirad** [comment]
Thanks, @vgenty, or helping! I think the build errors are from bin and lib folders not available. I added them to repo. Can you pull and try again?

**Comment by vgenty** [comment]
Builds fine and `ann_test` runs OK
https://goo.gl/1Y7smc

**Pull request merged**
